name: TotalEconomy
version: 1.0.0
main: com.ericgrandt.totaleconomy.TotalEconomy
description: All in one economy plugin for Minecraft
author: Eric
api-version: 1.19
depend:
- Vault
commands:
    balance:
        description: Retrieve the player's balance
        usage: /<command>
        permission: totaleconomy.balance